name: Deploy Projeto

on:
  push:
    branches:
      - main

jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: |
          if [ -e yarn.lock ]; then
          yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi

      - name: Build Project
        run: npm run build
      
      - name: Creating deployment artifact
        env: 
          GITHUB_SHA : ${{ github.sha}}
        run: tar -czf "${GITHUB_SHA}".tar.gz build
      
      - name: Storign artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-build
          path: ${{ github.sha}}.tar.gz
