name: Deploy Projeto

on:
  push:
    branches:
      - main

jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Install outras coisas
        run: npm ci --legacy-peer-deps

      - name: Build Project
        run: npm run build
      
      - name: Creating deployment artifact
        env: 
          GITHUB_SHA : ${{ github.sha}}
        run: tar -czf "${GITHUB_SHA}".tar.gz build
      
      - name: Storign artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-build
          path: ${{ github.sha}}.tar.gz
